### ISSUE TITLE
I'd like to join nix-community

### ISSUE THREAD

**Issue by datakurre** [nix-community/nix-community.github.io#2]
Hi, I'd like to join nix-community with enough permissions to be able to move projects here without losing "ownership" permissions.

**Comment by zimbatm** [comment]
Hi, welcome!

I've sent you an invite. It should be enough permission for you to move the repositories you think could benefit from a shared management. By default you retain admin rights on the repository once it's moved.

Don't forget to set `[maintainer=@datakurre]` in the project description once you've move the project over.

**Comment by zimbatm** [comment]
Closing the issue for now. Let me know if you hit any issues!

**Comment by datakurre** [comment]
@zimbatm Thanks. How should I be able top enable issues on a moved repository like https://github.com/nix-community/pip2nix ?

**Comment by zimbatm** [comment]
Your users had only "write" privileges. I changed it to "admin" and enabled the issues as well.

I don't know how to change github so it automatically gives "admin" on transferred repos so just ping me again if you transfer any other repos.
